name: Bug Report Form
description: File a bug Report for our Tilli Documentation
title: ["bug", "spelling error","wrong info or link"]
labels: ["bug","documentation"]
assignees:
  - Tilliforkids
  - Briandsouza-17
  - Hannah31George
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen and what went wrong?
    placeholder: Tell us what you see! Suggestions are welcome
    value: "A bug happened and here is a suggestion!"
  validations:
    required: true
- type: dropdown
  id: pages
  attributes:
    label: Which page in the documentation did you face the issue?
    multiple: true
    options:
      - Project Charter
      - Brand Guidelines
      - Logo
      - Color
      - Typography
      - Art Assets
      - Open Source Licenses
      - OS Strategy
      - Opensource Quality Assuarance Process
      - Contribution Guidelines
      - Getting started (Contribution Guidelines)
      - Insights and Feedback
      - Bug Reporting and Fixing
      - Feature Development
      - Design and Content Creation
      - Translation
      - Tilli community
      - Code of Conduct
      - Getting Started (User Documentation)
      - Content Creators
      - Parents
      - Teachers
      - Translators
      - Getting Started (Developer Documentation)
      - Tilli Server
      - IDE
      - Tilli Web App
      - Tilli Documentation
- type: dropdown
  id: priority
  attributes:
    label: priority
    description: "High Priority are must be completed as soon possible, Medium Priority= need to be completed but can wait after high priority items, Low Priority are \"nice to have\" changes."
    multiple: false
    options:
      - High Priority
      - Medium Priority
      - Low Priority
   validations:
    required: true
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://tillioss.github.io/docs/code-of-conduct)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
